name: "tauri linux setup"
description: "tauri linux setup"
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt update && sudo apt install -y \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
      shell: bash
