enableGlobalCache: true

nodeLinker: node-modules

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs

catalog:
  "@types/node": "22.19.3"
  vitest: "4.0.15"
  typescript: "5.9.3"
  tsdown: "0.18.3"
