enableGlobalCache: true

nodeLinker: node-modules

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-4.5.0.cjs

supportedArchitectures:
  os:
    - "darwin"
    - "linux"
    - "win32"
  cpu:
    - "x64"
    - "ia32"
    - "arm64"
  libc:
    - "glibc"
    - "musl"
