enableGlobalCache: true

nodeLinker: node-modules

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-4.10.2.cjs

supportedArchitectures:
  cpu:
    - x64
    - ia32
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32
