[target.aarch64-unknown-linux-musl]
linker    = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[target.'cfg(target_vendor = "apple")']
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup,-no_fixup_chains"]

[target.'cfg(all(target_os = "linux", target_env = "gnu"))']
rustflags = ["-C", "link-args=-Wl,--warn-unresolved-symbols", "-C", "link-args=-Wl,-z,nodelete"]

[target.'cfg(target_env = "msvc")']
rustflags = ["-C", "link-args=/FORCE"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
