name: "rust setup"
description: "rust setup"
inputs:
  components:
    description: "Comma-separated list of additional components to install."
    required: false
  targets:
    description: "Comma-separated list of additional targets to install."
    required: false
runs:
  using: "composite"
  steps:
    - name: Install rust
      id: install-rust
      uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
      with:
        toolchain: 1.91.0
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}
