name: "rust setup"
description: "rust setup"
inputs:
  components:
    description: "Comma-separated list of additional components to install."
    required: false
  bins:
    description: "Comma-separated list of global binaries to install into Cargo."
    required: false
  targets:
    description: "Comma-separated list of additional targets to install."
    required: false
  github-token:
    description: "GitHub token to use"
    required: false
  tauri:
    description: "Supports for tauri"
    required: false
runs:
  using: "composite"
  steps:
    - uses: moonrepo/setup-rust@v1
      with:
        components: ${{ inputs.components }}
        cache-base: main
        targets: ${{ inputs.targets }}
        bins: ${{ inputs.bins }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - if: ${{ inputs.tauri }}
      run: |
        sudo apt update && sudo apt install -y \
                 libwebkit2gtk-4.1-dev \
                 build-essential \
                 curl \
                 wget \
                 file \
                 libxdo-dev \
                 libssl-dev \
                 libayatana-appindicator3-dev \
                 librsvg2-dev
      shell: bash
