[package]
edition = "2021"
name    = "webview-bundle-electron-binding"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
doctest    = false
test       = false

[dependencies]
napi                    = { workspace = true, features = ["napi8", "async"] }
napi-derive             = { workspace = true }
thiserror               = { workspace = true }
tokio                   = { workspace = true, features = ["fs"] }
webview-bundle          = { workspace = true, features = ["async"] }
webview-bundle-protocol = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
