export const DEFAULT_CONFIG_FILES: string[] = [
  'wvb.config.js',
  'wvb.config.cjs',
  'wvb.config.mjs',
  'wvb.config.ts',
  'wvb.config.cts',
  'wvb.config.mts',
  'webview-bundle.config.js',
  'webview-bundle.config.cjs',
  'webview-bundle.config.mjs',
  'webview-bundle.config.ts',
  'webview-bundle.config.cts',
  'webview-bundle.config.mts',
  'wvb.config.json',
  'wvb.config.jsonc',
];
