/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parse(buf: Buffer): Promise<Bundle>
export type JsBundle = Bundle
export declare class Bundle {
  constructor()
  encode(): Buffer
}
