[package]
edition = "2021"
name    = "webview-bundle-cli"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
doctest    = false
path       = "binding/lib.rs"
test       = false

[dependencies]
napi                = { workspace = true, features = ["napi8"] }
napi-derive         = { workspace = true }
webview-bundle-napi = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
