[package]
authors     = ["Seokju Na <seokju.me@gmail.com>"]
description = "TBD"
edition     = "2021"
license     = "MIT"
name        = "webview-bundle-cli-node"
publish     = false
repository  = "https://github.com/seokju-na/webview-bundle"
version     = "0.0.0"

[lib]
crate-type = ["cdylib"]
doctest    = false
test       = false

[dependencies]
biome_console      = { workspace = true }
napi               = { workspace = true }
napi-derive        = { workspace = true }
webview-bundle-cli = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
