[package]
authors     = ["Seokju Na <seokju.me@gmail.com>"]
description = "TBD"
edition     = "2021"
license     = "MIT"
name        = "webview-bundle-cli-node"
publish     = false
repository  = "https://github.com/seokju-na/webview-bundle"
version     = "0.0.0"

[lib]
crate-type = ["cdylib"]
doctest    = false
test       = false

[dependencies]
webview-bundle-cli = { workspace = true }

# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
anyhow        = { workspace = true }
biome_console = { workspace = true }
bpaf          = { workspace = true }
napi          = { workspace = true }
napi-derive   = { workspace = true }
tokio         = { workspace = true, features = ["rt", "rt-multi-thread"] }

[build-dependencies]
napi-build = { workspace = true }
