name: "node setup"
description: "node setup"
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # 3.5.1
    - run: |
        corepack enable
        corepack prepare --activate
      shell: bash
    - id: yarn-cache-dir
      run: echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # 4.3.0
      with:
        path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-node-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-yarn-
