[package]
edition = "2021"
name    = "webview-bundle-node-binding"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
doctest    = false
test       = false

[dependencies]
napi           = { workspace = true }
napi-derive    = { workspace = true }
webview-bundle = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
